### ISSUE TITLE
panic in `"Creating new packages"`

### ISSUE THREAD

**Issue by zankich** [cloudfoundry/bosh-deployment-resource#30]
We're see the same issue as described in: https://github.com/cloudfoundry/bosh-cli/issues/311
```
panic: unmarshal chunk '{"time":1508430727,"stage":"Creating new packages","tags":[],"total":15,"task":"cc_uploader/af87cd817e22657daee717b72e27400e378cf9b5ec32d6f959d2{"time":1508430727,"stage":"Downloading remote release","tags":[],"total":1,"task":"Downloading remote release","index":1,"state":"started","progress":0}'

goroutine 60 [running]:
panic(0xcae120, 0xc420a4ad60)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/ui/task.(*ReporterImpl).showEvent(0xc420632120, 0x6, 0xc42007c280, 0x129)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/ui/task/reporter.go:110 +0x1a5e
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/ui/task.(*ReporterImpl).TaskOutputChunk(0xc420632120, 0x6, 0xc4204ee000, 0x9a, 0x8000)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/ui/task/reporter.go:94 +0x26c
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director.(*taskReporterWriter).Write(0xc4202c23a0, 0xc4204ee000, 0x9a, 0x8000, 0x9a, 0x13765a0, 0xc4200120f0)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director/task_client_request.go:155 +0x63
io.copyBuffer(0x1376ea0, 0xc4202c23a0, 0x1378a20, 0xc4203cee00, 0xc4204ee000, 0x8000, 0x8000, 0xd39080, 0xc42058c400, 0x1378a20)
	/usr/local/go/src/io/io.go:392 +0x260
io.Copy(0x1376ea0, 0xc4202c23a0, 0x1378a20, 0xc4203cee00, 0xc4203cee00, 0x0, 0x0)
	/usr/local/go/src/io/io.go:360 +0x68
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director.ClientRequest.readResponse(0xc420550040, 0x1b, 0x0, 0x0, 0x13863c0, 0xc4203ae640, 0x137f4e0, 0xc42018a420, 0x1386720, 0xc420532b70, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director/client_request.go:249 +0x2a4
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director.ClientRequest.RawGet(0xc420550040, 0x1b, 0x0, 0x0, 0x13863c0, 0xc4203ae640, 0x137f4e0, 0xc42018a420, 0x1386720, 0xc420532b70, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director/client_request.go:109 +0x350
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director.TaskClientRequest.reportOutputChunk(0xc420550040, 0x1b, 0x0, 0x0, 0x13863c0, 0xc4203ae640, 0x137f4e0, 0xc42018a420, 0x1386720, 0xc420532b70, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director/task_client_request.go:172 +0x248
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director.TaskClientRequest.WaitForCompletion(0xc420550040, 0x1b, 0x0, 0x0, 0x13863c0, 0xc4203ae640, 0x137f4e0, 0xc42018a420, 0x1386720, 0xc420532b70, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director/task_client_request.go:108 +0x2b5
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director.TaskClientRequest.waitForResult(0xc420550040, 0x1b, 0x0, 0x0, 0x13863c0, 0xc4203ae640, 0x137f4e0, 0xc42018a420, 0x1386720, 0xc420532b70, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director/task_client_request.go:129 +0xa2
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director.TaskClientRequest.PostResult(0xc420550040, 0x1b, 0x0, 0x0, 0x13863c0, 0xc4203ae640, 0x137f4e0, 0xc42018a420, 0x1386720, 0xc420532b70, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director/task_client_request.go:63 +0x157
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director.Client.UploadReleaseURL(0xc420550040, 0x1b, 0x0, 0x0, 0x13863c0, 0xc4203ae640, 0x137f4e0, 0xc42018a420, 0x1386720, 0xc420532b70, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director/releases.go:303 +0x334
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director.DirectorImpl.UploadReleaseURL(0xc420550040, 0x1b, 0x0, 0x0, 0x13863c0, 0xc4203ae640, 0x137f4e0, 0xc42018a420, 0x1386720, 0xc420532b70, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director/releases.go:219 +0xbe
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/director.(*DirectorImpl).UploadReleaseURL(0xc4205ba0c0, 0xc420517400, 0x7f, 0xc42026a570, 0x28, 0x1380000, 0xc420532b70, 0xc420550040)
	<autogenerated>:171 +0xe7
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd.UploadReleaseCmd.uploadRemote(0xc42018bd10, 0x137a260, 0xc4206321e0, 0x138a260, 0xc4205ba0c0, 0xc42018bd30, 0x13856a0, 0xc4203348c0, 0x1388d60, 0xc4205bc0c0, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd/upload_release.go:62 +0x84
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd.(UploadReleaseCmd).(github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd.uploadRemote)-fm(0xc420517400, 0x7f, 0x0, 0x0, 0x0, 0xc420524ca8, 0x8, 0xc42027c000, 0x3, 0x4, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd/upload_release.go:53 +0x73
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd.UploadReleaseCmd.uploadIfNecessary(0xc42018bd10, 0x137a260, 0xc4206321e0, 0x138a260, 0xc4205ba0c0, 0xc42018bd30, 0x13856a0, 0xc4203348c0, 0x1388d60, 0xc4205bc0c0, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd/upload_release.go:149 +0xe3
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd.UploadReleaseCmd.Run(0xc42018bd10, 0x137a260, 0xc4206321e0, 0x138a260, 0xc4205ba0c0, 0xc42018bd30, 0x13856a0, 0xc4203348c0, 0x1388d60, 0xc4205bc0c0, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd/upload_release.go:53 +0x3c7
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd.(*UploadReleaseCmd).Run(0xc420632240, 0xc420517400, 0x7f, 0x0, 0x0, 0x0, 0xc420524ca8, 0x8, 0xc42027c000, 0x3, ...)
	<autogenerated>:257 +0x9d
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd.ReleaseManager.createAndUploadRelease(0x1379fe0, 0xc4203ae680, 0x137a0e0, 0xc420632240, 0x5, 0xc420524ca8, 0x8, 0xc420524d30, 0x6, 0xc420517400, ...)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd/release_manager.go:144 +0x1c5
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd.ReleaseManager.parallelCreateAndUpload.func1(0xca5ce0, 0xc4203c2f00, 0xc4204aff68, 0x180001)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd/release_manager.go:65 +0x7f
github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd.WorkerPool.spawnWorker.func1(0xc4203c2f00, 0xc4203c2fc0, 0xc4203c2f60, 0xc4203c3020)
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd/worker_pool.go:63 +0x6e
created by github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd.WorkerPool.spawnWorker
	/tmp/build/80754af9/gopath/src/github.com/cloudfoundry/bosh-deployment-resource/vendor/github.com/cloudfoundry/bosh-cli/cmd/worker_pool.go:73 +0x5d
```

Looks like this bug was fixed in this commit: https://github.com/cloudfoundry/bosh-cli/commit/f58b3a1827c1f4359397485d781c16f102e4b430

Can this resource be updated with the bug fixes?

**Comment by drich10** [comment]
Released as part of [v2.7.0](https://github.com/cloudfoundry/bosh-deployment-resource/tree/v2.7.0)!
